apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: apache-autoscaler
  namespace: lab
  labels:
    app: apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 15