apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  namespace: lab
  labels:
    app: apache
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: apache-p
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80