apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
  namespace: lab
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # VER CUANTA CAPACIDAD ------------------------
  accessModes:
    - ReadWriteOnce # VER QUE TIPO DE ACCESO -------------------
  hostPath:
    path: "/data"