apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: postgres-autoscaler
  namespace: lab
  labels:
    app: postgres
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postgres-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 15