apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: lab
  labels:
    app: postgres
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: postgres-p
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 6666