apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-autoscaler
  namespace: lab
  labels:
    app: python
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 15