apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: lab
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-p
  template:
    metadata:
      labels:
        app: python-p
    spec:
      containers:
      - name: python-c
        image: # VER COMO ES LA IMAGEN CON EL REGISTRY
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 10
          periodSeconds: 60
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
        ports:
        - containerPort: 21000