apiVersion: v1
kind: Service
metadata:
  name: python-svc
  namespace: lab
  labels:
    app: apache
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: python-p
  ports:
  - protocol: TCP
    port: 80
    targetPort: 21000